### ISSUE TITLE
PM Review: Message Board

### ISSUE THREAD

**Issue by ckane30691** [ckane30691/Basechamp#12]

**Comment by s-pangburn** [comment]
1. Try to place "Post a message" at the top left the way it is on Basecamp to make it clearer that what's being posted are topics rather than comments. Alternatively, change the text to "Post a Topic"

2. The styling is adequate, but very similar to what you did with Todos, almost to the point where they don't feel like two separate pieces of functionality the way they should. I recommend trying to style either this or the other one closer to how it looks on Basecamp as best you can.

3. Comments on a message should be centered and preferably as wide as the message div above it. Again, please look to Basecamp and try to get the styling as close as possible to how it is on there.

**Comment by ckane30691** [comment]
Hey Stephen,

Got it.  I'll work on reworking the styles to match closer to basecamps and
I'll implement the other changes you mentioned as well. Look for changes on
heroku!

Thanks,
Cory
