### ISSUE TITLE
PM Review: Todos

### ISSUE THREAD

**Issue by ckane30691** [ckane30691/Basechamp#14]

**Comment by s-pangburn** [comment]
1. Center the create/edit Todo dialog (including both fields and the button), preferably make the text in the input and textarea fields the same font as the todo item itself. Also there's a bit too much padding between the "To-dos" header and the creation/edit form itself.

2. The red "X" is used both for deletion and closing the form you opened, which can be confusing for a user. Try making the ones that only close the dialog a different color, like black or blue, to show they are not dangerous or deleting any data. Also, maybe make this harmless version of "X" a little bigger, since the things you close tend to be a little bigger, it make it easier to find.

3. The "To-dos" header should be bigger. Remember, think in terms of heirarchy. Keep the elements on your page organized.

4. Since todos are added to the bottom, the button to add them should be at the bottom too. While Basecamp does have a button at the top of its todo page, it's for making an entirely new list, you'll notice adding todos are at the bottom of the list, where they'll eventually show up.

**Comment by s-pangburn** [comment]
Alright, looks good! Do whatever you feel you need to polish this feature off, I'll be marking this MVP as done.
