### ISSUE TITLE
PM Review: User Auth

### ISSUE THREAD

**Issue by ckane30691** [ckane30691/Basechamp#16]

**Comment by s-pangburn** [comment]
### Things to fix

1. Errors don't display at all. Please show login and signup errors on every form, including the homepage one.

2. Font sizing all around is a little off. Try to make it as close a match to Basecamp as possible. Logo font should be a smidge bigger, session buttons a little smaller, input field default text a little bigger and less bold (it's a little hard to read right now.) Basechamp site description underneath "We've been expecting you" should be larger or the margins should be brought in so that the text is spread out more evenly over two lines, similar to the Basecamp website.

3. Submit button should have more padding on left and right.

4. Signup form and "Try Basechamp Today" list should be more centered on the page. The Try Basechamp Today should all be on one line, and the list of features needs to be more spaced out, preferably with the checkmarks or some other type of bullet point there to make it more readable. 

5. Submit button between login and signup pages should be identical in styling. Header also needs to be more evenly aligned.

6. Logout button has more padding on the right than the left. Looks really awkward.

On the other hand, the auth functionality looks solid! Great job building things out so quickly, you're doing great!

**Comment by s-pangburn** [comment]
1. In your CSS for the "Try BaseChamp Today!", you should have width set to 100% instead of 50%, like so:
```
.call-to-action h3 {
    font-family: 'Merriweather', serif;
    width: 100%;
}
```
Otherwise the text get broken out over two lines instead of one, when it's really only three words.

2. Again, the bullet points under "Try BaseChamp Today!" should have an actual bullet point of some sort. Try `list-style-type`?

3.  The submit buttons are still different between the `/login` and `/signup` pages. They should look identical (the front page can be different, but since these two pages are formatted the same they should have identical buttons to look more cohesive)

4. Errors carry over and the form doesn't clear when you switch between login and signup.

5. The header "Just enter your username and password" should have more padding, particularly on the left and right but also the top and bottom. Space things out a little bit. Also avoid situations where you have one word on a line by itself after a line break. Tends to look very unprofessional. Ideally lines of text should be about evenly sized in terms of length, especially for titles.

It's really just styling and polish at this point. Once you have it together, let me know and I can take another look at it!

**Comment by s-pangburn** [comment]
Almost there! Your errors display at the left edge of the login box when you put in incorrect login information. It should be centered, or at the very least, not touching the edge! Also errors still carry over between the login and signup forms. Try getting the "Invalid username or password" error to show up and click on the signup link. You'll see the error persists.

Get those done and I'll mark this feature as complete!

**Comment by ckane30691** [comment]
Check out the latest version on heroku.  Errors are now rendering correctly per your message above.

**Comment by s-pangburn** [comment]
Good work! 👍
